import React from 'react';
import { Link } from 'react-router-dom';

const About = () => {
  return (
    <div className="container py-5 fade-in-up">
      {/* Header */}
      <div className="text-center mb-5">
        <span className="badge bg-success bg-opacity-25 text-success border border-success border-opacity-50 px-3 py-2 rounded-pill mb-2 fw-bold">
          OUR MISSION
        </span>
        <h1 className="display-4 text-dark mb-3">Fighting Climate Change Together</h1>
        <p className="text-muted lead max-w-2xl mx-auto">
          Understand the science of greenhouse gas emissions and discover how daily choices collectively impact the future of our biosphere.
        </p>
      </div>

      {/* Grid blocks */}
      <div className="row g-5 align-items-center mb-5">
        <div className="col-md-6">
          <img
            src="https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?auto=format&fit=crop&q=80&w=800"
            alt="Forest tree"
            className="img-fluid rounded-4 shadow-lg"
            style={{ width: '100%', height: '350px', objectFit: 'cover' }}
          />
        </div>
        <div className="col-md-6">
          <h2 className="text-dark mb-3">What is a Carbon Footprint?</h2>
          <p className="text-secondary mb-3">
            A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. On average, the global carbon footprint for a person is close to 4 tons. However, to avoid a 2°C rise in global temperatures, the average global carbon footprint per year needs to drop to under 2 tons by 2050.
          </p>
          <p className="text-secondary mb-4">
            Emissions come from heating our houses, charging smart devices, driving gasoline vehicles, manufacturing consumer products, and farming meat. EcoTrack helps you isolate the exact sectors causing your highest emissions.
          </p>
          <Link to="/calculator" className="btn btn-eco">
            Measure Your Footprint
          </Link>
        </div>
      </div>

      <div className="row g-4 my-5">
        <div className="col-md-4">
          <div className="card h-100 border-0 bg-white p-4 rounded-4 shadow-sm">
            <h5 className="text-success"><i className="bi bi-fire mr-2"></i> Greenhouse Effect</h5>
            <p className="text-secondary small">
              Carbon dioxide and methane build up in the atmosphere, creating a shield that prevents solar heat from radiating back into space, thereby causing global warming.
            </p>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card h-100 border-0 bg-white p-4 rounded-4 shadow-sm">
            <h5 className="text-success"><i className="bi bi-droplet-fill mr-2"></i> Rising Oceans</h5>
            <p className="text-secondary small">
              Glaciers are melting and sea temperatures are expanding, threatening coastal towns, islands, and delicate marine habitats worldwide.
            </p>
          </div>
        </div>
        <div className="col-md-4">
          <div className="card h-100 border-0 bg-white p-4 rounded-4 shadow-sm">
            <h5 className="text-success"><i className="bi bi-cloud-lightning-rain-fill mr-2"></i> Extreme Weather</h5>
            <p className="text-secondary small">
              Warming changes atmospheric systems, causing intense heatwaves, severe droughts, stronger hurricanes, and unpredictable flash floods.
            </p>
          </div>
        </div>
      </div>

      {/* How it works */}
      <div className="card border-0 bg-success bg-opacity-10 p-5 rounded-5 mt-5">
        <h3 className="text-center text-success mb-4">How EcoTrack Empowers You</h3>
        <div className="row g-4 text-center">
          <div className="col-sm-6 col-md-3">
            <h4 className="text-dark">1. Log</h4>
            <p className="text-secondary small">Enter transportation, energy, and diet habits in seconds.</p>
          </div>
          <div className="col-sm-6 col-md-3">
            <h4 className="text-dark">2. Analyze</h4>
            <p className="text-secondary small">Review charts to find hot-spots in your emissions.</p>
          </div>
          <div className="col-sm-6 col-md-3">
            <h4 className="text-dark">3. Set Targets</h4>
            <p className="text-secondary small">Establish goals and track reduction completion rates.</p>
          </div>
          <div className="col-sm-6 col-md-3">
            <h4 className="text-dark">4. Reward</h4>
            <p className="text-secondary small">Collect unique badges as you improve your habits.</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default About;
